forge 'forge.puppetlabs.com'

# Forge Modules
mod 'puppetlabs/ntp', '3.0.3'
mod 'puppetlabs/dashboard'
mod 'puppetlabs/mysql'
mod 'puppetlabs/apache'
mod 'puppetlabs/passenger'
mod 'puppetlabs/stdlib'
mod 'arnoudj/sudo'
mod 'zack/r10k'
mod 'puppetlabs/ruby'
mod 'puppetlabs/gcc'
mod 'puppetlabs/pe_gem'
mod 'croddy/make'
mod 'puppetlabs/inifile'
mod 'puppetlabs/vcsrepo'
mod 'puppetlabs/git'
mod 'gentoo/portage'
mod 'mthibaut/users'
mod 'maestrodev/wget'
